### ISSUE TITLE
Bootstart element Overlays

### ISSUE THREAD

**Issue by jasper502** [heelhook/chardin.js#101]
Does anyone have a decent fork that addresses the z-index issue well?  I wanted to use Chardin for my site vs. Intro but it's becomming a bit ugly to make work.

The theme I have uses Bootstrap and that seems to not play well:

![screen shot 2017-04-14 at 12 25 44 pm](https://cloud.githubusercontent.com/assets/1505829/25053126/9d64cec2-2112-11e7-9a39-d5e4521beef5.png)

I have issues with the bottom offset (this is likely my theme) but some of the elements (seems to be the button css from Bootstrap).

**Comment by SeanJA** [comment]
Do you have a mockup of what you are hoping for it to look like?

**Comment by gbjbaanb** [comment]
The new release should fix this.
