### ISSUE TITLE
Start with button

### ISSUE THREAD

**Issue by emresaracoglu** [heelhook/chardin.js#115]
Hello

I want to run it with the button and I tried to get the data via JSON but it doesn't work. Can you say my mistake?

```
<button type="button" class="btn btn-dual" id="tourStart" data-toggle="chardinjs"></button>
```

```
$('#tourStart').on('click', 'button[data-toggle="chardinjs"]', function (e) {
	e.preventDefault();
	$('body').chardinJs({url: "test/test.json"});
         return $('body').chardinJs('start');
});
```

**Comment by gbjbaanb** [comment]
I think the chardinjs() call must be previously instantiated as the examples show, so try it like that. and, of course, ensure the url is correct as you're using it in a relative path.

**Comment by emresaracoglu** [comment]
@gbjbaanb Thank you for your help.
I made additions but again the button did not work.

Change 1:
`<body data-chardin-sequenced="true" data-chardin-auto="false" data-chardin-delay="800" >`

Change 2:
```
$('body').chardinJs();
$('#tourStart').on('click', 'button[data-toggle="chardinjs"]', function (e) {
	e.preventDefault();
	$('body').chardinJs({url: "test/test.json"});
         return $('body').chardinJs('start');
});
```

**Comment by gbjbaanb** [comment]
put the url in the initial instance of chardinJS. it should be resettable as you're doing it.

Check the method used. I call it like this: 
`return ($('body').data('chardinJs')).toggle();`

check the network is trying to get the correct file in your browser though, I'm not sure if resetting the url like that works, but get it working the way the example does it, and then tweak.

**Comment by emresaracoglu** [comment]
Unfortunately, I was not successful

**1:** 

```
$('#tourStart').on('click', 'chardinJs:start', function () {
	('body').chardinJs({url: "--URL--others/appIntroTextEn.json"});
	return ($('body').data('chardinJs')).toggle();
});
```
**Result:**

I do not receive any errors and does not work
2:
 
```
$('body').chardinJs();
$('#tourStart').on('click', 'button[data-toggle="chardinjs"]', function (e) {
	e.preventDefault();
	$('body').chardinJs({url: "test/test.json"});
         return ($('body').data('chardinJs')).toggle();
});
```

**Result:**

I get this error:

> Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: start

**Comment by gbjbaanb** [comment]
I don't know how you got "unsupported pseudo 'start'" in that code you showed... try this.

$('body').chardinJs({url: test/test.json});
$('#tourStart').on('click', 'button[data-toggle="chardinjs"]', function (e) {
	e.preventDefault();
         return ($('body').data('chardinJs')).toggle();
});
