### ISSUE TITLE
Programmatic use

### ISSUE THREAD

**Issue by sabatale** [heelhook/chardin.js#116]
Is it possible to use chardin.js in a programmatic way for pages where you cannot make changes on the code? I can only see the option of adding _data-intro_ attributes to the HTML from the README.

**Comment by gbjbaanb** [comment]
I don't think so, the help popups need to know which elements to display against, and the data-intro provides that linkage. How else would you ensure a help popup be associated with an element (without building a whole selector engine into it, which I'm not going to do).

A way round it would be for you to alter the html programatically to add the data-intro attributes where you want them, and then call chardin.
