### ISSUE TITLE
*[data-intro] is a 'heavy' css query. Can I give you a list?

### ISSUE THREAD

**Issue by pahlers** [heelhook/chardin.js#16]
First of all, I like the tool. It looks great! 

But I'm concerned with one thing. *[data-intro] is a 'heavy' css query. It's not optimised for speed. When you have a big page with a lot of elements. Things will be slowed down.

Instead of that, can I give you list? Like:

``` javascript
var list = [
    {
        target: '.jumbotron img',
        intro: 'An awesome 18th-century painter, who found beauty in everyday, common things.',
        position: 'right'
    },
    {
        target: '.jumbotron .btn',
        intro: 'This button toggles the overlay, you can click it, even when the overlay is visible',
        position: 'left'
    },
    {
        target: '.jumbotron .credits p',
        intro: 'Author of this plugin, aka Pablo Fernandez',
        position: 'right'
    },
]

$('body').chardinJs(list);
$('body').chardinJs('start');
```

That would be awesome. Now I even can pre-i18n it.

Big thanks
##

**Comment by gbjbaanb** [comment]
version 0.2.0 has this feature, though the list is sourced dynamically via a get request.
