### ISSUE TITLE
Elements with overflow: hidden that contain very tall elements

### ISSUE THREAD

**Issue by jedgrant** [heelhook/chardin.js#18]
When you apply Chardin to something like this.

< div id="wrapper" style="overflow:hidden; height: 350px;" data-intro="Stuff" data-position="right">
    < div id="content" style="height: 100000px">< /div>
< /div>

It creates a line as tall as the hidden element. It also causes some other issues when scrolling the page such as causing the text to disappear.
##

**Comment by gbjbaanb** [comment]
hidden elements are no longer tooltipped.
