### ISSUE TITLE
Element with z-index and position doesn't appear above overlay

### ISSUE THREAD

**Issue by dozyatom** [heelhook/chardin.js#26]
When the element to highlight has both a z-index and either position relative or absolute, it doesn't rise above the overlay.

Reproduced here: http://jsfiddle.net/wAUKV/
##

**Comment by maksad** [comment]
@fskandrani can you please explain more precisely how does your hack work if I am using https://github.com/mendhak/angular-intro.js

**Comment by fskandrani** [comment]
@maksad can you detail what part of the code you don't understand? it would be a pleasure to help you

**Comment by maksad** [comment]
@fskandrani, thank you very much for your response. Fortunately, I fixed it. The problem was with webkit browsers and making `-webkit-perspective: none;` solved my issue.
