### ISSUE TITLE
Is there a way to make it mobile responsive?

### ISSUE THREAD

**Issue by scooterlord** [heelhook/chardin.js#39]
Hello everyone. I have been looking for quite some time an overlay instructions script to use for an upcoming project.

I am wondering if it can be made responsive down to mobile screen size; what I mean is turn the left or right side tooltips to top and bottom when it reaches mobile screen size.

Moreover, is there any way to replace the borders with an image (like arrows?)

Thanks in advance for any help I get on this :)
##

**Comment by danialm** [comment]
+1

**Comment by girvo** [comment]
+1

**Comment by gbjbaanb** [comment]
I have a change in the new release where you can get the tooltips (and their position) from a json file, deliberately for this - return a different file on mobile and this would work.
