### ISSUE TITLE
Chardin.js demo (gh-pages) doesn't work due to some http refernces

### ISSUE THREAD

**Issue by MrCsabaToth** [heelhook/chardin.js#62]
Right now I'm booted into Win 8.1, trying latest FF and Chrome. Looks like google fonts are not loaded and maybe other issues.

FF FireBug console:
Blocked loading mixed active content "http://fonts.googleapis.com/css?family=Montserrat:400,700"
Blocked loading mixed active content "http://code.jquery.com/jquery-1.9.1.min.js"
Blocked loading mixed active content "http://fonts.googleapis.com/css?family=Montserrat:400,700"
Blocked loading mixed active content "http://code.jquery.com/jquery-1.9.1.min.js"
TypeError: t is undefined
...tParent;return t.top=r,t.left=n,t},e}(),t.fn.extend({chardinJs:function(){var n,...
chardinjs.min.js (line 2, col 3983)
ReferenceError: $ is not defined
$(function() {
demo.js (line 4, col 2)
GET https://apis.google.com/_/scs/apps-static/_/js/k=...RSTNoBcAYOn7vC-V1AIz10SRkEhEcPg/cb=gapi.loaded_0

200 OK
        248ms  
fastbut...9063390 (line 28)
GET https://apis.google.com/_/scs/apps-static/_/js/k=...RSTMjG9wWLrT-KZYIA_lqG6d1J68HKw/cb=gapi.loaded_1

200 OK
        251ms  
fastbut...9063390 (line 28)
20:1:41.407 CSI/tbsd_
20:1:41.408 CSI/_tbnd

Chrome:
[blocked] The page at 'https://heelhook.github.io/chardin.js/#' was loaded over HTTPS, but ran insecure content from 'http://fonts.googleapis.com/css?family=Montserrat:400,700': this content should also be loaded over HTTPS.
 (index):11
[blocked] The page at 'https://heelhook.github.io/chardin.js/#' was loaded over HTTPS, but ran insecure content from 'http://code.jquery.com/jquery-1.9.1.min.js': this content should also be loaded over HTTPS.
 (index):1
Uncaught TypeError: Cannot read property 'fn' of undefined chardinjs.min.js:2
Uncaught ReferenceError: $ is not defined demo.js:4
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1406859257.html:1
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) follow_button.1406859257.html:1
##

**Comment by gbjbaanb** [comment]
appears to work now. thanks
