### ISSUE TITLE
Helper layer top padding should be margin?

### ISSUE THREAD

**Issue by Cottin** [heelhook/chardin.js#64]
When using `data-position="top"` the little line is not padded above the element it gives tip for:

![image](https://cloud.githubusercontent.com/assets/4736419/4517948/52fc0c08-4c65-11e4-94b9-ee19021dd948.png)

I fix this by changing `&.chardinjs-top { border-top: solid white 1px; padding-top: 10px; }` to `&.chardinjs-top { border-top: solid white 1px; margin-top: -10px; }` and voilà:

![image](https://cloud.githubusercontent.com/assets/4736419/4517955/a179f55c-4c65-11e4-86ac-67f051ae9635.png)

I haven't seen any side-effects yet, but I haven't tested it too much either.
##

**Comment by abunsen** [comment]
Would it be ok if I issued a PR for this?

**Comment by gbjbaanb** [comment]
appears to be fixed now.
