### ISSUE TITLE
Chardin.js and Intro.js conflict in data-intro attribute use

### ISSUE THREAD

**Issue by rhyous** [heelhook/chardin.js#84]
Both Chardin.js and Intro.js use the data-intro attribute.

I would like to have a walk-thru for first use with Intro.js and a separate help overlay using chardin.js. It is hokey to have the help file be a walk-thru and it is hokey to have the help overlay popup on first use without a walk thru. It seems to me that both have their place.

Unfortunately they both use the same attribute: data-intro 

So I can't use them both wiithout changing one or the other. I would change chardin.js to use data-help instead of data-intro. Chardin.js is more of a help file overlay while intro.js is more of an intro and walk-thru on first use tool. So data-intro makes more sense for Intro.js.

I see how I can change this easy enough myself if I branch chardin.js. I just thought someone might have some feedback on this.

Changing this would break everyone who currently uses chardin.js. If I were to provide a pull request, it wouldn't be pulled.

So perhaps the solution would be to default to data-intro but allow for the attribute to be changed at load time.

Thoughts?
##

**Comment by SeanJA** [comment]
I think I have this working in my fork, I made some changes so that you can pass in a settings object instead of the string like this:

````js
$('body').chardinJS({
    'attribute': 'data-my-intro',
    'method': 'start' // start or stop, or toggle
});
````

you can still do this as well: `$('body').chardinJS('start');` and it defaults to using `data-intro`

**Comment by rhyous** [comment]
Thanks SeanJA!

**Comment by rhyous** [comment]
Did I mention I tested this and it works well? 

I have it in dev environment only right but it will be in production probably before December.

**Comment by SeanJA** [comment]
:+1:

**Comment by gbjbaanb** [comment]
I merged your changes in, hopefully it works as you expect now.
