### ISSUE TITLE
Make the opacity of the overlay configurable

### ISSUE THREAD

**Issue by MrCsabaToth** [heelhook/chardin.js#88]
Right now .8 is wired into the code:

```
        return setTimeout(function() {
          styleText += "opacity: .8;";
          return overlay_layer.setAttribute("style", styleText);
        }, 10);
```
##

**Comment by MrCsabaToth** [comment]
For my application 0.4 seems better

**Comment by clintharris** [comment]
+1

**Comment by clintharris** [comment]
In the meantime, you can manually set the opacity each time after showing the chardin layer (the second opacity transition is hard to notice):
```
var myOpacity = 0.5;
$('body').chardinJs('start');
setTimeout(() => { $('.chardinjs-overlay').css('opacity', myOpacity); }, 100);
```

**Comment by MrCsabaToth** [comment]
Thanks, I'll try that

**Comment by MrCsabaToth** [comment]
Works, but the => notation is ECMAScript 6, which caught IE11 off guard.
So let's stay with

    setTimeout(function() { $('.chardinjs-overlay').css('opacity', myOpacity); }, 100);

**Comment by ConfusedVorlon** [comment]
or just change it in css

```
  .chardinjs-overlay {
    opacity:0.6 !important;
  }
```

**Comment by gbjbaanb** [comment]
It is no longer in the code, just the css so you can edit/override that to whatever opacity you like.
