### ISSUE TITLE
Doesn't work with SVG elements

### ISSUE THREAD

**Issue by goodspeedj** [heelhook/chardin.js#94]
I'm trying to get chardinjs to work on SVG elements, but no luck.  Only the shaded overlay appears (normal HTML elements work fine).

`<svg width="100" height="100">
    <rect width="100" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" data-intro="An awesome 18th-century painter, who found beauty in everyday, common things." data-position="right" />
    </svg>`
##

**Comment by gbjbaanb** [comment]
I have chardin working with a SVG, but the svg is wrapped in an anchor tag and the anchor has the attribute. I think a div or similar should work OK.
