### ISSUE TITLE
Multiple trigger points, multiple sets of contextual help

### ISSUE THREAD

**Issue by saltcod** [heelhook/chardin.js#95]
Hey!   Love Chardin so far. Great work. 

Quick question: I'm looking to have two sets of contextual help for an app. One set for the overall interface and another for individual parts of the specific page I'm on. 

Any idea how I might create separate "Help" and a "Help on this page" toggles that lead to separate sets of contextual help? 

Thanks! 
##

**Comment by gbjbaanb** [comment]
the new release allows you to source the tooltips from a json file, you should be able to set 2 buttons with different urls, any data-tooltips not present in the file are ignored so you can put data-intro everywhere and only display the ones present in the file.
